import { generateScenarioBatch } from "../services/geminiService.js";
import {
  determineCorrectOption,
  validateRuleIds,
} from "../services/rulesEngine.js";

export async function getScenario(req, res) {
  try {
    const { type, difficulty } = req.body;

    const scenarios = await generateScenarioBatch(type, difficulty);

    for (const scenario of scenarios) {
      // Determine the correct answer using the rules engine
      const result = determineCorrectOption(
  type,
  scenario.phase || null,
  scenario.options
);

      // Ignore Gemini's "correct" field
      scenario.correct = result.correct;

      // Ignore Gemini's "ruleIds" field
      scenario.ruleIds = result.ruleIds;

      // Validate the rule IDs generated by our rules engine
      if (!validateRuleIds(type, scenario.ruleIds)) {
        throw new Error(
          `Generated invalid rule IDs for ${type}.`
        );
      }
    }

    res.json(scenarios);
  } catch (error) {
    console.error(error);

    res.status(500).json({
      message: "Failed to generate scenarios.",
    });
  }
}